### ISSUE TITLE
Услуги [backend]

### ISSUE THREAD

**Issue by nikitarub** [uburu/prof#12]
### БД
- [x] Buyer - покупатель услуги 
- [x] Author - создатель услуги 
- [x] Название услуги 
- [x] Категория услуги (тего-подобно) ["лекция", "консультация", "тестирование", "репититорство", "мероприятие", "другое"]
- [x] Теги профессий (берутся из списка желаемых профессий)
- [x] Описание услуги 
- [x] Кол-во человек купивших услугу
- [x] Комментарии к услуге 
     - [x] Текст
     - [x] Автор
     - [x] Время
- [x] Цена

### Создание услуги
- [x] Название услуги 
- [x] Категория услуги (тего-подобно)
- [x] Теги профессии
- [x] Описание услуги 
- [x] Цена

### Список услуг
то же самое, только вывод списком:
- [x] Название услуги 
- [x] Автор услуги
- [x] Категория услуги (тего-подобно)
- [ ] Теги профессий
- [x] Описание услуги 
- [ ] Кол-во человек купивших услугу
- [ ] Комментарии к услуге 
     - [ ] Текст
     - [ ] Автор
     - [ ] Время
- [x] Цена

### Купленные услуги
Как предыдущее, только с привязкой к покупателю

### Созданные услуги 
Так же список, только с привязкой к создателю
+ 
- [x] Список купивших услугу

**Comment by Ermako27** [comment]
у меня один вопрос: почему студент не может узнать кто создал ту или иную услугу и когда он это сделал

**Comment by Ermako27** [comment]
У нас есть какой-то конкретный перечень услуг, которые специалист может создать или любой специалист может создать любую услугу по своему усмотрению?
